### PR TITLE
Added Countdown timer

### PR DESCRIPTION
**Pull request by Rebeccals**
I changed and added the Countdown component.

### CODE REVIEW

**Review by christopherjlo — CHANGES_REQUESTED** [review]
Looks Good! All that's left is to add the words "days", "hours", "minutes", and "seconds" to the timer! If you have any questions, please refer to the Issue on the project board and also feel free to ask a tech lead!
Link to project board if u forgot:  [Static-Site Board](https://github.com/orgs/BroncoHacks-Website/projects/1/views/7)

**Comment by Rebeccals** [comment]
I added the labels for Days, Hours, Minutes, seconds. Do I have to do another pull request or does this one still push the new changes I just did?

**Comment by chillwafflez** [comment]
> I added the labels for Days, Hours, Minutes, seconds. Do I have to do another pull request or does this one still push the new changes I just did?

This pull request will still push the new changes!

**Review by DanielPasion — APPROVED** [review]
Looks good thanks fo the documentation

**Pull request merged**
